<a href="https://colab.research.google.com/github/satyayenamandra/deeplearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover most fundamental concepts on Deep learning

Intro to tensors
getting info from tensors
manipulating tensors
tensors & numpy
using @tf.function
using GPUs with tensorflow(TPUs)
Extercies

  

In [1]:
# Import Tensor Flow

import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for a number of dimensions)

scalar.ndim

0

In [4]:
# Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# create a matrix (has more than 1 dimension)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix with data type

another_matrix = tf.constant([[10.,7.],
                              
                              [3.2,2.],
                              [8.,9.]], dtype=tf.float16) # Specify the data type with precision

another_matrix                              

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 3.2,  2. ],
       [ 8. ,  9. ]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Lets create a tensor

tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

**What we have created so far**

* Scalar is a single number
* Vector is a number with direction (wind speed & direction)
* Matrix is a 2-dimensional array of number
* Tensor an n-dimensional array of numbers (when n can be any number, a 0 dimentional tensor is a scalar, 1-dimentional tensor can be a vector)

Creating Tensors with tf.variable

In [12]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Lets try changing one of the elements in our changeable tensor

changeable_tensor[0]=7

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating Random tensors

Random tensors are tensors with some arbitrary size which contain random numbers

In [ ]:
# create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1== random_2

### Shuffle Random tensors in a tensor



In [ ]:
# Shuffle a tensor (valueable for when you want to shuffle your data with inherent order not valuable)

not_shuffled = tf.constant( [[10,7],
                             [3,4],
                             [5,6]])

not_shuffled.ndim

tf.random.set_seed(42) # Global level seed

tf.random.shuffle(not_shuffled,seed=42  ) # Operation level seed

In [ ]:
# create a tensor of all ones

tf.ones([10,7])

In [ ]:
# create a tensor of all Zeros

tf.zeros([3,4])

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing)

In [ ]:
# You can also turn NumPy arrays into tensors

import numpy as np
numpy_A = np.arange (1, 25, dtype=np.int32) # Creates a numpy array between 1 to 25
numpy_A
# x = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector 

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

### Getting Information from Tensors

When dealing with tensors, we need to be aware of the following attributes:

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a Rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3, 4, 5))
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor :", rank_4_tensor.shape)
print("Elements along the 0 axis :", rank_4_tensor.shape[0])
print("Elements along the last axis :", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :", tf.size(rank_4_tensor))
print("Total number of elements in our tensor :", tf.size(rank_4_tensor).numpy())

### Indexing Tensors

Tensors can be indexed just like in Python lists

In [ ]:
some_list = [1,2,3,4]
print(some_list[:2])
print(some_list[3:4])

In [ ]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1, :1, :1,:]


In [ ]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[10,7],
                             [5,8]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" is the final axis

In [ ]:
# Adding axis at the beginning
tf.expand_dims(rank_2_tensor, axis=0)

### Manipulating tensors (tensor operations)

**Basic  Operations**

+, -, *, /

In [ ]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10,7], [3,4]])
tensor+10

In [ ]:
#Original tensor is unchanged
tensor

In [ ]:
# Multiplication
tensor * 10

In [ ]:
#Division
tensor / 2

In [ ]:
# We can use the tensorflow built-in function too

tf.multiply(tensor, 10)

### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations

There are 2 rules to fulfill:

1. The inner dimension must match
2. The resulting matrix has the shape of inner dimensions

In [14]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


InvalidArgumentError: ignored

In [15]:
tensor * tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[ 49,  64,  81],
        [100, 121, 144]],

       [[169, 196, 225],
        [256, 289, 324]]], dtype=int32)>

In [17]:
# Matrix multiplication with python Operation "@"

tensor @ tensor

InvalidArgumentError: ignored

In [18]:
tensor.shape

TensorShape([3, 2, 3])

In [19]:
# Create a tensor of (3,2)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

#create another (3, 2 ) tensor

y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

#y= tf.constant(y, shape=(2,3))

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [20]:
 #Let's change the shape of Y
print(x.shape, tf.reshape(y, shape=(2,3)).shape)

 x @ tf.reshape(y, shape=(2,3))


(3, 2) (2, 3)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [21]:
# can do the same with transpose

x, tf.transpose(x), tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [22]:
# Try matrix multiplication with transpose rather than reshape

tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The DOT Product**

Matrix multiplication is also referred to as the dot product

Can be performed using:
* `tf.matmul()`
* `tf.tensordot()`

In [23]:


x, y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [24]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(x),y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [25]:
# Perform matrix multiplication between x and y (transposed)

tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [26]:
# Perform matrix multiplication between x and y (reshaped)

tf.matmul(x, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [27]:
# Check the values of y, respsahpe y and transposed y

print("Normal Y: ")
print(y, "\n")

print("Y reshaped :")
print(tf.reshape(y, (2,3)),"\n")

print("Y transposed :" )
print(tf.transpose(y),"\n")

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally, when performing matrix multiplication of 2 tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [28]:
# Create a new tensor with default dataype (float32)

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [29]:
C = tf.constant([3,5])
C.dtype

tf.int32

In [30]:
# Change from float32 to float 16 (reduced preciion)

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [31]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>,
 tf.float32)

###Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [32]:
# Get the absolute values

D = tf.constant([-7, -10])
print(D)
tf.abs(D)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [35]:
# Create a random to find min, max, mean and sum 
import numpy as np

randInt = tf.constant(np.random.randint(0,100, size=50))
print(randInt)

#Find Minimum
print(tf.reduce_min(randInt))

#Finding minimum in Numpy
print(np.min(randInt))


# Finding Maximum
tf.reduce_max(randInt)

# Finding Mean
tf.reduce_mean(randInt)

# SUm of a Tensor
tf.reduce_sum(randInt)



tf.Tensor(
[84 66 62 35 96 86 41 65 24 81 83  4 36 23 90 55 16 91 39  0 26 40 64 98
 18 36 39  1 68 66  5 22 98 72 53 93 23 52 35 69 83 25 12  9 51 49 32 44
 76  1], shape=(50,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
0


<tf.Tensor: shape=(), dtype=int64, numpy=2437>

In [42]:
# Finding Variance

import tensorflow_probability as tfp #Importing probability library

print(tfp.stats.variance(randInt)) # Using Probability library
print(tf.math.reduce_variance(tf.cast(randInt,dtype=tf.float32))) # Using Math library
print(tf.math.reduce_std(tf.cast(randInt, dtype=tf.float32)))


tf.Tensor(856, shape=(), dtype=int64)
tf.Tensor(856.3924, shape=(), dtype=float32)
tf.Tensor(29.264183, shape=(), dtype=float32)


### Finding the positional Maximum and Minimum

To identify at which index of the tensor does the maximum value occur ?

In [46]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [47]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [49]:
# Index on our largest value position

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [51]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [52]:
# Check for equality

assert F[tf.argmax(F)] == tf.reduce_max(F)

In [53]:
# Find the positional minimum

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [54]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [58]:
### Squeezing a Tensor (removing all single dimensions)

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [59]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [64]:
## Removes single dimensions in the tensors

G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors



In [67]:
# Create a list of indices
some_list = [0,1,2,3] # assuming to be red, green, blue, purple

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [68]:
# To specify custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value="I love deep learning", off_value="I like Guitar")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I like Guitar', b'I like Guitar',
        b'I like Guitar'],
       [b'I like Guitar', b'I love deep learning', b'I like Guitar',
        b'I like Guitar'],
       [b'I like Guitar', b'I like Guitar', b'I love deep learning',
        b'I like Guitar'],
       [b'I like Guitar', b'I like Guitar', b'I like Guitar',
        b'I love deep learning']], dtype=object)>

### Squaring, log, square root

In [69]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [71]:
# Finding squares

tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [73]:
# Finding Square root

tf.math.sqrt(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [75]:
# Finding log
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>