<a href="https://colab.research.google.com/github/satyayenamandra/deeplearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover most fundamental concepts on Deep learning

Intro to tensors
getting info from tensors
manipulating tensors
tensors & numpy
using @tf.function
using GPUs with tensorflow(TPUs)
Extercies

  

In [3]:
# Import Tensor Flow

import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim stands for a number of dimensions)

scalar.ndim

0

In [6]:
# Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [9]:
# create a matrix (has more than 1 dimension)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [14]:
# Create another matrix with data type

another_matrix = tf.constant([[10.,7.],
                              
                              [3.2,2.],
                              [8.,9.]], dtype=tf.float16) # Specify the data type with precision

another_matrix                              

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 3.2,  2. ],
       [ 8. ,  9. ]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [15]:
# Lets create a tensor

tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

**What we have created so far**

* Scalar is a single number
* Vector is a number with direction (wind speed & direction)
* Matrix is a 2-dimensional array of number
* Tensor an n-dimensional array of numbers (when n can be any number, a 0 dimentional tensor is a scalar, 1-dimentional tensor can be a vector)

Creating Tensors with tf.variable

In [17]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# Lets try changing one of the elements in our changeable tensor

changeable_tensor[0]=7

TypeError: ignored

In [20]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored