<a href="https://colab.research.google.com/github/satyayenamandra/deeplearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover most fundamental concepts on Deep learning

Intro to tensors
getting info from tensors
manipulating tensors
tensors & numpy
using @tf.function
using GPUs with tensorflow(TPUs)
Extercies

  

In [ ]:
# Import Tensor Flow

import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for a number of dimensions)

scalar.ndim

0

In [ ]:
# Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a matrix (has more than 1 dimension)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix with data type

another_matrix = tf.constant([[10.,7.],
                              
                              [3.2,2.],
                              [8.,9.]], dtype=tf.float16) # Specify the data type with precision

another_matrix                              

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 3.2,  2. ],
       [ 8. ,  9. ]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor

tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                       [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

**What we have created so far**

* Scalar is a single number
* Vector is a number with direction (wind speed & direction)
* Matrix is a 2-dimensional array of number
* Tensor an n-dimensional array of numbers (when n can be any number, a 0 dimentional tensor is a scalar, 1-dimentional tensor can be a vector)

Creating Tensors with tf.variable

In [ ]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Lets try changing one of the elements in our changeable tensor

changeable_tensor[0]=7

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating Random tensors

Random tensors are tensors with some arbitrary size which contain random numbers

In [ ]:
# create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1== random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle Random tensors in a tensor



In [ ]:
# Shuffle a tensor (valueable for when you want to shuffle your data with inherent order not valuable)

not_shuffled = tf.constant( [[10,7],
                             [3,4],
                             [5,6]])

not_shuffled.ndim

tf.random.set_seed(42) # Global level seed

tf.random.shuffle(not_shuffled,seed=42  ) # Operation level seed

In [ ]:
# create a tensor of all ones

tf.ones([10,7])

In [ ]:
# create a tensor of all Zeros

tf.zeros([3,4])

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing)

In [ ]:
# You can also turn NumPy arrays into tensors

import numpy as np
numpy_A = np.arange (1, 25, dtype=np.int32) # Creates a numpy array between 1 to 25
numpy_A
# x = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting Information from Tensors

When dealing with tensors, we need to be aware of the following attributes:

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a Rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3, 4, 5))
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor :", rank_4_tensor.shape)
print("Elements along the 0 axis :", rank_4_tensor.shape[0])
print("Elements along the last axis :", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :", tf.size(rank_4_tensor))
print("Total number of elements in our tensor :", tf.size(rank_4_tensor).numpy())

### Indexing Tensors

Tensors can be indexed just like in Python lists

In [ ]:
some_list = [1,2,3,4]
print(some_list[:2])
print(some_list[3:4])

In [ ]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1, :1, :1,:]


In [ ]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[10,7],
                             [5,8]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" is the final axis

In [ ]:
# Adding axis at the beginning
tf.expand_dims(rank_2_tensor, axis=0)

### Manipulating tensors (tensor operations)

**Basic  Operations**

+, -, *, /

In [ ]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10,7], [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Division
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
# We can use the tensorflow built-in function too

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations

There are 2 rules to fulfill:

1. The inner dimension must match
2. The resulting matrix has the shape of inner dimensions

In [ ]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with python Operation "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Create a tensor of (3,2)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

#create another (3, 2 ) tensor

y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

#y= tf.constant(y, shape=(2,3))

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
 #Let's change the shape of Y
print(x.shape, tf.reshape(y, shape=(2,3)).shape)

 x @ tf.reshape(y, shape=(2,3))


(3, 2) (2, 3)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# can do the same with transpose

x, tf.transpose(x), tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape

tf.matmul(tf.transpose(x),y)

**The DOT Product**

Matrix multiplication is also referred to as the dot product

Can be performed using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:


x, y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(x),y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y (transposed)

tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y (reshaped)

tf.matmul(x, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of y, respsahpe y and transposed y

print("Normal Y: ")
print(y, "\n")

print("Y reshaped :")
print(tf.reshape(y, (2,3)),"\n")

print("Y transposed :" )
print(tf.transpose(y),"\n")

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally, when performing matrix multiplication of 2 tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default dataype (float32)

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([3,5])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float 16 (reduced preciion)

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>,
 tf.float32)

###Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values

D = tf.constant([-7, -10])
print(D)
tf.abs(D)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
# Create a random to find min, max, mean and sum 

randInt = tf.constant(np.random.randint(0,100, size=50))
print(randInt)

#Find Minimum
print(tf.reduce_min(randInt))

#Finding minimum in Numpy
print(np.min(randInt))


# Finding Maximum
tf.reduce_max(randInt)

# Finding Mean
tf.reduce_mean(randInt)

# SUm of a Tensor
tf.reduce_sum(randInt)



tf.Tensor(
[11 12 25 12 68 15 81  1  9  8 62 26 74 87  5 89 29  4 81 92 63  3 84 97
 27 89  7 57 17  9 80 29 12 61 46 27 98 50  5  2 28 85  8  3 59 45 28 63
 71 51], shape=(50,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
1


<tf.Tensor: shape=(), dtype=int64, numpy=2095>

In [ ]:
# Finding Variance

tf.math.reduce_variance(randInt)

tf.math.reduce_std(randInd)

TypeError: ignored